# Define a list of ports that are managed by BGP. These ports
# connect to other BGP enabled devices
#bgp_managed_ports: []

# prefix of the spine switches. covers 254 devices. override if needed
# used to determine the loopback ip of the spine switch
spine_prefix: 10.1.2
# prefix for leaf switches. covers 254 devices. override if needed
# used to determine the loopback ip of the leaf switch
leaf_prefix: 10.1.1

# leaf ASN starting point. add asn from here.
leaf_asn_start: 65100

# spine ASN starting point
spine_asn_start: 65500

# ports associated to leaf toredge-br SVI interface
svi_ifaces: []

# ports associated with leaf k8s ports
# svi IP that all TOR devices connect to
# define this in host vars or on the inventory group entry of the leaf
# svi_ip: ""

# List of router IPs of k8s hosts acting of router reflector clients
# Example k8s_ips: ['192.168.1.1', '192.168.1.2']
k8s_ips: []
