- name: configure l2 interfaces
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  notify: reload l2

- name: install pip so that you can do pip install docker.py
  apt: name=python-pip

- name: install docker.py so that docker_container ansible keyword will work
  pip: name=docker-py
