- name: configure l2 interfaces
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  notify: reload l2

- name: install pip so that you can do pip install docker.py
  apt: name=python-pip

- name: install netshow for troubleshooting
  pip: name=netshow-linux-lib

- name: adjust sysctl to optimize L3 routing on the server
  copy:
    src: 99quagga_defaults.conf
    dest: /etc/sysctl.d/99quagga_defaults.conf
    owner: root
    group: root
    mode: 0644
  notify: reload sysctl
