- block:
  - name: |
      determine the host number of the server. assumes hostname is as follows
      /[a-z0-9]*-k8s[1-9]?[0-9]*/. Example snv-k8s1. something like snv-k8s02 will not
      work
    set_fact:
      k8s_ip_suffix: "{{ ansible_hostname.split('k8s')[1] }}"

  - name: set loopback address
    set_fact:
      loopback_ip: "{{ k8s_ip_prefix }}.{{k8s_ip_suffix}}"

  - name: set BGP asn number
    set_fact:
       bgp_asn: "{{ k8s_asn_start  + k8s_ip_suffix|int }}"

  when: "{{ 'k8s' in ansible_hostname }}"

- name: configure l2 interfaces
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  notify: reload l2

- name: adjust sysctl to support router on a host
  copy:
    src: 99quagga_defaults.conf
    dest: /etc/sysctl.d/99quagga_defaults.conf
    owner: root
    group: root
    mode: 0644
  notify: reload sysctl

- name: enable BGP in quagga
  copy:
    src: daemons
    dest: /etc/quagga/daemons
    owner: root
    group: root
    mode: 0644
  notify: reload l3

- name: configure BGP config in quagga.conf
  template:
    src: Quagga.conf.j2
    dest: /etc/quagga/Quagga.conf
    owner: root
    group: root
    mode: 0644
  notify: reload l3

- name: install Quagga container
  docker_container:
    name: quagga
    image: linuxsimba/quagga:xenial-latest
    privileged: yes
    network_mode: host
    tty: yes
    volumes:
      - /etc/quagga/Quagga.conf:/etc/quagga/Quagga.conf
      - /etc/quagga/daemons:/etc/quagga/daemons


